- id: dts-format
  name: DTS Format
  description: Auto-format DeviceTree source files
  language: node
  entry: dts-linter-hook --quiet --formatFixAll
  files: '\.(dts|dtsi|overlay|keymap)$'

- id: dts-lint
  name: DTS Lint
  description: Lint DeviceTree source files
  language: node
  entry: dts-linter-hook
  files: '\.(dts|dtsi|overlay|keymap)$'
