- id: dts-format
  name: DTS Format
  description: Auto-format DeviceTree source files
  language: node
  entry: dts-linter --formatFixAll
  args: [--file]
  files: '\.(dts|dtsi|overlay|keymap)$'
  additional_dependencies: ['dts-linter@0.5.0']

- id: dts-lint
  name: DTS Lint
  description: Lint DeviceTree source files
  language: node
  entry: dts-linter
  args: [--file]
  files: '\.(dts|dtsi|overlay|keymap)$'
  additional_dependencies: ['dts-linter@0.5.0']
